version: '3.5'
services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: piche
    ports:
      - "5432:5432"
    restart: unless-stopped
